import { z } from 'zod';

/**
 * Baby Name Game types for Before We Were Three
 * Defines the data model for AI-powered name generation, voting, and match tracking
 */

/**
 * Valid choices when voting on a generated name
 */
export type NameVoteChoice = 'love' | 'maybe' | 'nope';

/**
 * A name generated by the AI with origin, meaning, and notes
 */
export interface GeneratedName {
  id: string;
  roundId: string;
  name: string;
  origin: string[];   // Array per prompt contract (multiple origins allowed)
  meaning: string;
  notes: string;
  sortOrder: number;
}

/**
 * State of a single name within a round (includes vote status)
 */
export interface NameVoteState {
  name: GeneratedName;
  myVote: NameVoteChoice | null;
  partnerVoted: boolean;
}

/**
 * GET /api/name-game/:envelopeId response for current round
 */
export interface NameGameRoundResponse {
  roundId: string;
  roundNumber: number;
  names: NameVoteState[];
  allVoted: boolean;   // Both partners finished voting on all names
}

/**
 * Results after both partners finish voting on a round
 */
export interface NameGameResults {
  matches: GeneratedName[];          // Both loved
  nearMisses: GeneratedName[];       // One loved + one maybe
  worthDiscussing: GeneratedName[];  // Both said maybe
  myVotes: Record<string, NameVoteChoice>;
  partnerVotes: Record<string, NameVoteChoice>;
}

/**
 * Accumulated matches across all rounds
 */
export interface NameGameMatchList {
  matches: GeneratedName[];
}

/**
 * Pending guidance state — tracks submissions for a round not yet generated
 */
export interface PendingGuidanceState {
  roundNumber: number;
  myGuidanceSubmitted: boolean;
  partnerGuidanceSubmitted: boolean;
}

/**
 * Full state response for the name game activity
 */
export interface NameGameStateResponse {
  currentRound: NameGameRoundResponse | null;
  allMatches: GeneratedName[];
  roundCount: number;
  pendingGuidance?: PendingGuidanceState;
}

/**
 * POST /api/name-game/:nameId/vote response
 */
export interface SubmitNameVoteResponse {
  allVoted: boolean;
  results?: NameGameResults;
}

// ============================================================
// Zod Schemas for request validation
// ============================================================

/**
 * POST /api/name-game/:envelopeId/guidance request body
 * Same shape as generateNamesRequestSchema — records readiness with optional preferences
 */
export const submitGuidanceRequestSchema = z.object({
  guidance: z.string().max(500).optional(),
});

export type SubmitGuidanceRequest = z.infer<typeof submitGuidanceRequestSchema>;

/**
 * Response from POST /api/name-game/:envelopeId/guidance
 * Discriminated union based on `status`:
 * - waiting_for_partner: guidance recorded, waiting for partner
 * - round_generated: generation happened, round is ready
 */
export type SubmitGuidanceResponse =
  | { status: 'waiting_for_partner'; roundNumber: number }
  | { status: 'round_generated'; round: NameGameRoundResponse };

/**
 * POST /api/name-game/:nameId/vote request body
 */
export const submitVoteRequestSchema = z.object({
  choice: z.enum(['love', 'maybe', 'nope']),
});

export type SubmitVoteRequest = z.infer<typeof submitVoteRequestSchema>;

// ============================================================
// SignalR/Socket.io message types
// ============================================================

/**
 * SignalR message: A participant submitted a vote on a name
 */
export interface NameVoteSubmittedMessage {
  type: 'name_vote_submitted';
  roundId: string;
  participantId: string;
  namesVotedCount: number;   // Progress indicator
  totalNames: number;
}

/**
 * SignalR message: Both participants finished voting, round results ready
 */
export interface NameRoundCompleteMessage {
  type: 'name_round_complete';
  roundId: string;
  results: NameGameResults;
}

/**
 * SignalR message: A new round of names was generated
 * Broadcast to the partner who didn't trigger generation
 */
export interface NameRoundGeneratedMessage {
  type: 'name_round_generated';
  round: NameGameRoundResponse;
}

/**
 * SignalR message: Partner submitted guidance for the next round
 * Broadcast so the other participant's UI can show an indicator
 */
export interface NameGuidanceSubmittedMessage {
  type: 'name_guidance_submitted';
  roundNumber: number;
  participantId: string;
}
