import { z } from 'zod';

/**
 * Baby Name Game types for Before We Were Three
 * Defines the data model for AI-powered name generation, voting, and match tracking
 */

/**
 * Valid choices when voting on a generated name
 */
export type NameVoteChoice = 'love' | 'maybe' | 'nope';

/**
 * A name generated by the AI with origin, meaning, and notes
 */
export interface GeneratedName {
  id: string;
  roundId: string;
  name: string;
  origin: string[];   // Array per prompt contract (multiple origins allowed)
  meaning: string;
  notes: string;
  sortOrder: number;
}

/**
 * State of a single name within a round (includes vote status)
 */
export interface NameVoteState {
  name: GeneratedName;
  myVote: NameVoteChoice | null;
  partnerVoted: boolean;
}

/**
 * GET /api/name-game/:envelopeId response for current round
 */
export interface NameGameRoundResponse {
  roundId: string;
  roundNumber: number;
  names: NameVoteState[];
  allVoted: boolean;   // Both partners finished voting on all names
}

/**
 * Results after both partners finish voting on a round
 */
export interface NameGameResults {
  matches: GeneratedName[];          // Both loved
  nearMisses: GeneratedName[];       // One loved + one maybe
  worthDiscussing: GeneratedName[];  // Both said maybe
  myVotes: Record<string, NameVoteChoice>;
  partnerVotes: Record<string, NameVoteChoice>;
}

/**
 * Accumulated matches across all rounds
 */
export interface NameGameMatchList {
  matches: GeneratedName[];
}

/**
 * Full state response for the name game activity
 */
export interface NameGameStateResponse {
  currentRound: NameGameRoundResponse | null;
  allMatches: GeneratedName[];
  roundCount: number;
}

// ============================================================
// Zod Schemas for request validation
// ============================================================

/**
 * POST /api/name-game/:envelopeId/generate request body
 */
export const generateNamesRequestSchema = z.object({
  guidance: z.string().max(500).optional(),
});

export type GenerateNamesRequest = z.infer<typeof generateNamesRequestSchema>;

/**
 * POST /api/name-game/:nameId/vote request body
 */
export const submitVoteRequestSchema = z.object({
  choice: z.enum(['love', 'maybe', 'nope']),
});

export type SubmitVoteRequest = z.infer<typeof submitVoteRequestSchema>;

// ============================================================
// SignalR/Socket.io message types
// ============================================================

/**
 * SignalR message: A participant submitted a vote on a name
 */
export interface NameVoteSubmittedMessage {
  type: 'name_vote_submitted';
  roundId: string;
  participantId: string;
  namesVotedCount: number;   // Progress indicator
  totalNames: number;
}

/**
 * SignalR message: Both participants finished voting, round results ready
 */
export interface NameRoundCompleteMessage {
  type: 'name_round_complete';
  roundId: string;
  results: NameGameResults;
}
